/**
 * Adaptador de conexión y cliente preparado para Supabase
 * Permite alternar entre Supabase Cloud y almacenamiento local persistente (LocalStorage)
 */

import { Client } from '../types';

export interface SupabaseConfig {
  url: string;
  anonKey: string;
  isConfigured: boolean;
}

export interface SupabaseClientRecord {
  id: string;
  client_number?: number;
  name: string;
  cif: string;
  address?: string;
  phone?: string;
  email?: string;
  plates?: string[];
  notes?: string;
  created_at?: string;
  updated_at?: string;
}

export interface SupabaseShortLinkRecord {
  id: string; // e.g. doc_P260002 or EXP-2026-001 or s_a3k9
  target_url: string;
  doc_number?: string;
  expediente?: string;
  payload?: any;
  created_at?: string;
}

/**
 * Script SQL para ejecutar en el Editor SQL de Supabase para añadir las tablas necesarias
 */
export const SUPABASE_ADD_CLIENT_NUMBER_COLUMN_SQL = `
-- Añadir columna de número identificador único a la tabla gestarian_clients en Supabase
ALTER TABLE gestarian_clients 
ADD COLUMN IF NOT EXISTS client_number BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- Índice único para garantizar rapidez y unicidad por número identificador
CREATE UNIQUE INDEX IF NOT EXISTS idx_gestarian_clients_client_number 
ON gestarian_clients(client_number);

COMMENT ON COLUMN gestarian_clients.client_number IS 'Número identificador secuencial y único de cada cliente (ID correlativo 1, 2, 3...)';

-- Tabla para almacenar los Enlaces Cortos de Documentos y Expedientes (gestarian.com)
CREATE TABLE IF NOT EXISTS gestarian_short_links (
  id TEXT PRIMARY KEY,
  target_url TEXT NOT NULL,
  doc_number TEXT,
  expediente TEXT,
  payload JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
`;

export function getSupabaseConfig(): SupabaseConfig {
  const env = (import.meta as unknown as { env?: Record<string, string> }).env || {};
  const url = env.VITE_SUPABASE_URL || '';
  const anonKey = env.VITE_SUPABASE_ANON_KEY || '';
  const isConfigured = Boolean(url && anonKey && !url.includes('your-project'));

  return {
    url,
    anonKey,
    isConfigured,
  };
}

/**
 * Cliente ligero para interactuar con la API REST de Supabase PostgREST
 * si el usuario añade sus credenciales en .env
 */
export async function supabaseRestQuery<T>(
  table: string,
  method: 'GET' | 'POST' | 'PATCH' | 'DELETE' = 'GET',
  body?: unknown,
  searchParams?: string
): Promise<{ data: T | null; error: string | null }> {
  const config = getSupabaseConfig();
  if (!config.isConfigured) {
    return { data: null, error: 'Supabase no configurado; utilizando almacenamiento local.' };
  }

  try {
    const queryStr = searchParams ? `?${searchParams}` : '';
    const res = await fetch(`${config.url}/rest/v1/${table}${queryStr}`, {
      method,
      headers: {
        'apikey': config.anonKey,
        'Authorization': `Bearer ${config.anonKey}`,
        'Content-Type': 'application/json',
        'Prefer': method === 'POST' ? 'return=representation' : 'return=minimal',
      },
      body: body ? JSON.stringify(body) : undefined,
    });

    if (!res.ok) {
      const errText = await res.text();
      return { data: null, error: errText };
    }

    const data = await res.json().catch(() => null);
    return { data, error: null };
  } catch (err: unknown) {
    return { data: null, error: err instanceof Error ? err.message : 'Error desconocido de red' };
  }
}

/**
 * Convierte un cliente de la aplicación al formato de registro de tabla en Supabase (con client_number)
 */
export function mapClientToSupabase(client: Client): SupabaseClientRecord {
  return {
    id: client.id,
    client_number: client.clientNumber,
    name: client.name,
    cif: client.cif,
    address: client.address,
    phone: client.phone,
    email: client.email,
    plates: client.plates || [],
    notes: client.notes,
    updated_at: new Date().toISOString(),
  };
}

/**
 * Convierte un registro de Supabase al tipo Client del frontend
 */
export function mapSupabaseToClient(record: SupabaseClientRecord): Client {
  return {
    id: record.id,
    clientNumber: record.client_number,
    name: record.name,
    cif: record.cif,
    address: record.address || '',
    phone: record.phone || '',
    email: record.email || '',
    plates: record.plates || [],
    notes: record.notes || '',
  };
}

/**
 * Sincroniza un cliente con Supabase de forma transparente (si Supabase está configurado)
 */
export async function syncClientToSupabase(client: Client): Promise<{ success: boolean; clientNumber?: number }> {
  const config = getSupabaseConfig();
  if (!config.isConfigured) {
    return { success: true, clientNumber: client.clientNumber };
  }

  const payload = mapClientToSupabase(client);
  const result = await supabaseRestQuery<SupabaseClientRecord[]>('gestarian_clients', 'POST', payload);

  if (result.data && result.data[0]) {
    return { success: true, clientNumber: result.data[0].client_number };
  }
  return { success: !result.error };
}

/**
 * Sincroniza un enlace corto con Supabase de forma transparente
 */
export async function syncShortLinkToSupabase(
  shortId: string,
  targetUrl: string,
  docNumber?: string,
  expediente?: string,
  payload?: any
): Promise<{ success: boolean }> {
  const config = getSupabaseConfig();
  if (!config.isConfigured) {
    return { success: true };
  }

  const record: SupabaseShortLinkRecord = {
    id: shortId,
    target_url: targetUrl,
    doc_number: docNumber,
    expediente,
    payload,
    created_at: new Date().toISOString(),
  };

  const result = await supabaseRestQuery<SupabaseShortLinkRecord[]>('gestarian_short_links', 'POST', record);
  return { success: !result.error };
}

/**
 * Consulta un enlace corto guardado en Supabase
 */
export async function fetchShortLinkFromSupabase(
  shortId: string
): Promise<SupabaseShortLinkRecord | null> {
  const config = getSupabaseConfig();
  if (!config.isConfigured) {
    return null;
  }

  const result = await supabaseRestQuery<SupabaseShortLinkRecord[]>(
    'gestarian_short_links',
    'GET',
    undefined,
    `id=eq.${encodeURIComponent(shortId)}`
  );

  if (result.data && result.data[0]) {
    return result.data[0];
  }
  return null;
}

