-- Migración oficial de Supabase (PostgreSQL) para Gestarian
-- Objetivo: Añadir columna de número identificador único correlativo (client_number) para cada cliente

-- 1. Si la tabla no existe previamente, crearla con todas sus columnas y el número identificador
CREATE TABLE IF NOT EXISTS gestarian_clients (
    id TEXT PRIMARY KEY,
    client_number BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    name TEXT NOT NULL,
    cif TEXT NOT NULL,
    address TEXT,
    phone TEXT,
    email TEXT,
    plates TEXT[] DEFAULT '{}',
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Si la tabla ya existe, añadir la columna client_number de manera segura e idempotente
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 
        FROM information_schema.columns 
        WHERE table_name = 'gestarian_clients' 
          AND column_name = 'client_number'
    ) THEN
        ALTER TABLE gestarian_clients 
        ADD COLUMN client_number BIGINT GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;

-- 3. Crear índice único para garantizar rapidez y unicidad por número identificador
CREATE UNIQUE INDEX IF NOT EXISTS idx_gestarian_clients_client_number 
ON gestarian_clients(client_number);

-- 4. Índice para búsquedas por CIF y Nombre
CREATE INDEX IF NOT EXISTS idx_gestarian_clients_cif ON gestarian_clients(cif);
CREATE INDEX IF NOT EXISTS idx_gestarian_clients_name ON gestarian_clients(name);

-- 5. Comentarios de documentación en el catálogo de PostgreSQL
COMMENT ON COLUMN gestarian_clients.client_number IS 'Número identificador secuencial y único de cada cliente (ID correlativo 1, 2, 3...)';
COMMENT ON TABLE gestarian_clients IS 'Cartera de clientes de Gestarian sincronizada con Supabase';
