export const GESTARIAN_SPEC_TEXT = `# GESTARIAN - ESPECIFICACIÓN TÉCNICA Y ARQUITECTURA DEL SISTEMA

**Aplicación Minimalista de Presupuestos y Facturas para Autónomos y Pequeñas Empresas**
*Documento de Referencia y Plan de Desarrollo Continuo*

---

## 1. IDENTIDAD Y PALETA VISUAL
- Estilo: Minimalista sobrio, sin textos de relleno ni ornamentos que distraigan.
- Fondo: Tono hueso (Off-white / Alabaster: #F8F7F3).
- Tipografía: Gris oscuro (#1E293B) y negro carbón (#0F172A).
- Gamas principales:
  * Base: Hueso (#F8F7F3, #F3F2EB).
  * Grises: Neutros fríos y cálidos (#F1F5F9, #E2E8F0, #94A3B8, #64748B, #334155).
  * Azules: Azul marino ejecutivo y slate blue (#0F2942, #1E3A8A, #2563EB).
- Estructura Header:
  * Arriba izquierda: [NUEVO USUARIO]
  * Arriba centro: GESTARIAN (todo en mayúsculas, espaciado minimalista)
  * Arriba derecha: [ÁREA DE CLIENTES]

---

## 2. OFERTAS Y MODELOS DE SERVICIO (DASHBOARD)
1. LITE:
   - Creación directa de Presupuestos y Facturas.
   - Opción con/sin IVA y casilla específica para marcar IVA 21%.
   - Conversión automática de presupuesto a factura.
   - Generación directa de factura.
   - Guardado en base de datos.
   - Botón de compartir nativo del dispositivo (navigator.share) con alternativa de copiado.
2. PRO:
   - Todo lo de Lite más:
   - Almacenamiento unificado de clientes, presupuestos y facturas en base de datos.
   - Informes fiscales trimestrales para gestoría (1T, 2T, 3T, 4T).
   - Generación de libros de facturas compatibles con A3, SAGE y hojas de cálculo XML / XLS Excel.
   - Agenda de citas para clientes.
   - Flujo automático: cuando un presupuesto es aceptado, se activa la agenda para concertar cita con el cliente.
3. ENTERPRISE:
   - Para pequeñas empresas y despachos profesionales.
   - Múltiples series de facturación (Serie Ordinaria A, Rectificativas R, Proyectos P).
   - Retención de IRPF configurable (15%, 7%, exento).
   - Auditoría y exportaciones contables avanzadas.

---

## 3. REGLA CRÍTICA DE INMUTABILIDAD FISCAL
- Fase Borrador: La factura y presupuesto pueden ser modificados, corregidos o eliminados.
- Fase Confirmada: La factura es revisada y validada antes de enviarla.
- Fase Enviada: En el momento en que se envía la factura al cliente:
  * Queda terminantemente bloqueada.
  * No se puede modificar ni el presupuesto vinculado ni la factura emitida, cumpliendo estrictamente con la normativa española de facturación y trazabilidad.

---

## 4. REGISTRO DE USUARIO Y VALIDACIÓN POR EMAIL
- Campos obligatorios:
  1. Nombre completo / Razón social
  2. Dirección fiscal completa (Calle, CP, Población, Provincia)
  3. CIF / NIF
  4. Número de teléfono
  5. Correo electrónico
- Flujo de verificación:
  - Envío de código numérico de 6 dígitos al correo proporcionado.
  - Verificación en pantalla antes de dar de alta activa al emisor fiscal.

---

## 5. INTEGRACIÓN RESEND (ENVÍO DE EMAILS)
- Arquitectura preparada para API de Resend (api.resend.com/emails).
- Envío de código de confirmación de registro (verification_code).
- Envío formal de facturas y presupuestos a clientes con archivo o enlace seguro.

---

## 6. ESQUEMA DE BASE DE DATOS SUPABASE (POSTGRESQL)
Tablas preparadas:
- gestarian_users: Emisores fiscales, NIF, domicilio, verificación y plan.
- gestarian_clients: Cartera de clientes, contacto, CIF y columna oficial \`client_number\` (BIGINT GENERATED BY DEFAULT AS IDENTITY / número identificador único correlativo).
  - Migración SQL disponible: \`/supabase/migrations/20260918_add_client_number_column.sql\`.
- gestarian_documents: Presupuestos y facturas con items, impuestos, estado y cerrojo de inmutabilidad (is_locked).
- gestarian_appointments: Citas y agenda vinculadas a presupuestos aceptados.

---

## 7. FORMATOS DE EXPORTACIÓN GESTORÍA
1. XLS / XML (Excel compatible): Libro oficial de Facturas Emitidas.
2. SAGE: CSV de diario contable (Cuentas 430, 705, 477).
3. A3: Fichero de enlace para A3ASESOR / A3eco.

---

## 8. RECONOCIMIENTO ÓPTICO DE MATRÍCULAS (PLATE RECOGNIZER ALPR)
- Integración con Plate Recognizer Snapshot API (api.platerecognizer.com/v1/plate-reader/).
- Proxy backend seguro en Express (\`/api/plate-recognizer\`) para proteger la API Key del lado cliente (\`PLATE_RECOGNIZER_API_KEY\`).
- Captura mediante cámara del dispositivo o subida de imagen (JPG/PNG).
- Detección automática de matrícula (formato europeo con banda azul 'E' y estándar internacional), nivel de confianza y tipo de vehículo (turismo, furgoneta, SUV, moto).
- Vinculación directa en presupuestos, facturas y fichas de clientes para talleres mecánicos, flotas, transportistas y peritajes.
- Búsqueda global por matrícula en el registro documental y cartera de clientes.

---

## 9. REPOSITORIO GITHUB Y CONTROL DE VERSIONES
- URL del repositorio configurable mediante la variable de entorno \`GITHUB_REPO_URL\`.
- Acceso directo en el header y en el banner de arquitectura del sistema.
- Control de versiones y trazabilidad de despliegue en producción.

---

## 10. ARQUITECTURA DEL SISTEMA: PORTAL DE USUARIO VS. PORTAL DE CLIENTES
1. **Portal de Usuario (Aplicación de Taller / ERP Gestarian)**:
   - Es el portal y software de gestión interna que opera el taller piloto (DM CAR) y los usuarios de Gestarian (lo que se desarrolla aquí).
   - Centraliza la gestión de expedientes, solicitudes, cartera de clientes y vehículos, presupuestos técnicos con o sin fijación de precios según permisos, agenda de citas, órdenes de trabajo (OTs), facturación oficial inmutable, balances económicos, proveedores e incidencias.
   - Integra control de accesos granular por empleado con asignación modular de vistas y capacidades operativas (cámara OCR ALPR, creación de presupuestos, gestión de OTs y fijación de precios reservada a jefatura).

2. **Portal de Clientes (Área de Clientes Externa)**:
   - Es el portal de acceso para los clientes finales (particulares y empresas) para consultar y hacer seguimiento de sus reparaciones y vehículos.
   - Dispone de 3 vías de acceso sincronizadas:
     a) **Página principal de gestarian.com**: Botón de acceso directo a "Área de Clientes" donde el usuario introduce su matrícula o número de expediente.
     b) **Enlaces directos enviados con los Presupuestos**: Al remitir un presupuesto al cliente, el sistema genera automáticamente un enlace para el seguimiento de su expediente vinculado en tiempo real (\`https://www.gestarian.com/clientes/expediente/{expedienteId}\`).
     c) **Descarga de la App del Portal del Cliente**: Enlace directo de descarga (\`https://www.gestarian.com/app-clientes\`) enviado en el mismo mensaje:
        - Vía **WhatsApp** para clientes particulares.
        - Vía **Email** para empresas y personas jurídicas (sociedades con CIF).
`;
